version: '3.9'

services:
  app:
    build: .
    container_name: mks-api
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mksnetwork
    env_file:
      - .env.docker

  db:
    build: .docker/postgres
    container_name: mksdb-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=mksdb
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "mksdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mksnetwork

  redis:
    container_name: cache
    image: redis
    ports:
      - 6380:6380
    volumes:
      - redis:/data
    networks:
      - mksnetwork

volumes:
  redis:
    driver: local

networks:
  mksnetwork:
    driver: bridge
