version: '3.1'

services:
  db:
    build: .
    container_name: mksdb-db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/dbdata
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=mksdb

  dbtest:
    build: .
    container_name: mksdb-test-db
    restart: always
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=mksdb
